# These are supported funding model platforms

github: [Vae-Scrooge]
# patreon: # Uncomment to enable Patreon
# open_collective: # Uncomment to enable Open Collective
# ko_fi: # Uncomment to enable Ko-fi
# tidelift: # Uncomment to enable Tidelift
# community_bridge: # Uncomment to enable Community Bridge
# liberapay: # Uncomment to enable Liberapay
# issuehunt: # Uncomment to enable IssueHunt
# otechie: # Uncomment to enable Otechie
# custom: ["https://www.buymeacoffee.com/yourusername"] # Uncomment with your custom URL
